app = "tcg-world-backend"
primary_region = "sea"

[build.args]
  NODE_ENV = "production"

[build]
  dockerfile = "./Dockerfile"

[deploy]
  release_command = "yarn prisma migrate deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1